version: 2

updates:

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: '04:00'
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(cicd):"

  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
      time: '04:00'
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(go):"

  - package-ecosystem: docker
    directory: "/.github/go/"
    schedule:
      interval: daily
      time: '04:00'
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(go):"